services:
  client:
    build: ../filmpal-client
    container_name: filmpal-client
    ports:
      - 5173:5173
    depends_on:
      server:
        condition: service_healthy

  server:
    build: ../filmpal-server
    container_name: filmpal-server
    ports:
      - 8080:8080
    environment:
      - OPENAI_API_KEY
      - OMDB_API_KEY
    healthcheck:
      test: ["CMD", "curl", "http://filmpal-server:8080/actuator/health"]
      start_period: 20s
    depends_on:
      database:
        condition: service_healthy

  database:
    image: container-registry.oracle.com/database/free:latest
    container_name: filmpal-database
    ports:
      - 1521:1521
    environment:
      - ORACLE_PWD
    healthcheck:
      test: ["CMD", "/opt/oracle/checkDBStatus.sh"]
      start_period: 20s
